# Generated by Django 5.2.5 on 2025-08-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BusTracker", "0004_rename_distance_cm_routesegment_distance_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busrealtime",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
