# Generated by Django 5.2.5 on 2025-08-31 04:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BusTracker", "0005_alter_busrealtime_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routesegment",
            name="distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="routesegment",
            name="geometry",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
