# Generated by Django 5.2.5 on 2025-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BusTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="routesegment",
            name="distance_cm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
