# Generated by Django 5.2.5 on 2025-08-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BusTracker", "0003_routesegment_distance_cm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routesegment",
            old_name="distance_cm",
            new_name="distance_km",
        ),
    ]
